apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-2
  template:
    metadata:
      name: shell-demo
      labels: 
        app: stress-2
    spec:
      priorityClassName: high-priority
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "800Mi"
            cpu: "1"
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
