apiVersion: v1
kind: Pod
metadata:
  name: shell-demo-2
spec:
  nodeSelector:
    kubernetes.io/hostname: node1
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "1200Mi"
        cpu: "1"
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
